### ISSUE TITLE
Color resetting after a while

### ISSUE THREAD

**Issue by Barraguesh** [PapirusDevelopmentTeam/papirus-folders#23]
- Distribution (version): Fedora 33 and 34
- Desktop environment: GNOME
- Installing method: Papirus Installer (Script)

After a while (I use the color Teal) I see the color reset to the original default color, blue.

**Comment by SmartFinn** [comment]
This happens after an update papirus-icon-theme because the papirus-folders script remaps symlinks directly in the icon theme. Some packages (e.g. PPA and [Papirus Installer](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#root-directory-recommended)) have post-install hook to restore color. If you have installed papirus-icon-theme by another way see [Restore the last used color from a config file](https://github.com/PapirusDevelopmentTeam/papirus-folders#restore-the-last-used-color-from-a-config-file).
